PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS competence;
CREATE TABLE competence (
	id INTEGER NOT NULL PRIMARY KEY,
	idParent INTEGER DEFAULT NULL,
	name TEXT,
	
	FOREIGN KEY (idParent) REFERENCES competence (id)
);

DROP TABLE IF EXISTS knowledge;
CREATE TABLE knowledge (
	id INTEGER NOT NULL PRIMARY KEY,
	idParent INTEGER DEFAULT NULL,
	name TEXT NOT NULL,
	semester INTEGER,
	
	FOREIGN KEY (idParent) REFERENCES knowledge (id)
);

DROP TABLE IF EXISTS knowHow;
CREATE TABLE knowHow (
	id INTEGER NOT NULL PRIMARY KEY,
	idCompetence INTEGER NOT NULL,
	name TEXT NOT NULL,
	
	FOREIGN KEY (idCompetence) REFERENCES competence (id)
);

DROP TABLE IF EXISTS knowledgeByCompetence;
CREATE TABLE knowledgeByCompetence (
	idCompetence INTEGER NOT NULL,
	idKnowledge INTEGER NOT NULL,
	
	FOREIGN KEY (idCompetence) REFERENCES competence (id),
	FOREIGN KEY (idKnowledge) REFERENCES knowledge (id)
);

INSERT INTO competence (id, idParent, name) VALUES
	(1, null, "Analyser"),
	(2, 1, "Identifier le besoin et appréhender les problématiques"),
	(3, 2, null),
	(4, 2, null),
	(5, 1, "Définir les frontières de l'analyse"),
	(6, 5, null),
	(7, 5, null),
	(8, 1, "Appréhender les analyses fonctionnelle et structurelle"),
	(9, 8, null),
	(10, 8, null),
	(11, 8, null),
	(12, 8, null),
	(13, 8, null),
	(14, 8, null),
	(15, 8, null),
	(16, 8, null),
	(17, 8, null),
	(18, 8, null),
	(19, 8, null),
	(20, 1, "Caractériser des écarts"),
	(21, 20, null),
	(22, 1, "Apprécier la pertinence et la validité des résultats"),
	(23, 22, null),
	(24, 22, null),
	(25, null, "Modéliser"),
	(26, 25, "Identifier et caractériser les grandeurs physiques agissant sur un système"),
	(27, 26, null),
	(28, 26, null),
	(29, 26, null),
	(30, 26, null),
	(31, 26, null),
	(32, 25, "Proposer un modèle de connaissance et de comportement"),
	(33, 32, null),
	(34, 32, null),
	(35, 32, null),
	(36, 32, null),
	(37, 32, null),
	(38, 32, null),
	(39, 32, null),
	(40, 32, null),
	(41, 32, null),
	(42, 32, null),
	(43, 32, null),
	(44, 32, null),
	(45, 32, null),
	(46, 32, null),
	(47, 32, null),
	(48, 32, null),
	(49, 32, null),
	(50, 32, null),
	(51, 25, "Valider un modèle"),
	(52, 51, null),
	(53, 51, null),
	(54, 51, null),
	(55, 51, null),
	(56, null, "Résoudre"),
	(57, 56, "Choisir une démarche de résolution"),
	(58, 57, null),
	(59, 57, null),
	(60, 57, null),
	(61, 57, null),
	(62, 57, null),
	(63, 56, "Procéder à la mise en œuvre d’une démarche de résolution analytique"),
	(64, 63, null),
	(65, 63, null),
	(66, 63, null),
	(67, 63, null),
	(68, 63, null),
	(69, 63, null),
	(70, 63, null),
	(71, 63, null),
	(72, 63, null),
	(73, 63, null),
	(74, 63, null),
	(75, 63, null),
	(76, 63, null),
	(77, 56, "Procéder à la mise en œuvre d’une démarche de résolution numérique"),
	(78, 77, null),
	(79, 77, null),
	(80, null, "Expérimenter"),
	(81, 80, "Découvrir le fonctionnement d’un système pluri-technologique"),
	(82, 81, null),
	(83, 81, null),
	(84, 80, "Proposer et justifier un protocole expérimental"),
	(85, 84, null),
	(86, 84, null),
	(87, 84, null),
	(88, 84, null),
	(89, 84, null),
	(90, 84, null),
	(91, 80, "Mettre en œuvre un protocole expérimental"),
	(92, 91, null),
	(93, 91, null),
	(94, 91, null),
	(95, 91, null),
	(96, 91, null),
	(97, 91, null),
	(98, 91, null),
	(99, 91, null),
	(100, null, "Concevoir"),
	(101, 100, "Imaginer des architectures ou des solutions technologiques"),
	(102, 101, null),
	(103, 101, null),
	(104, 101, null),
	(105, 100, "Choisir une solution technologique"),
	(106, 105, null),
	(107, 105, null),
	(108, 105, null),
	(109, 105, null),
	(110, 105, null),
	(111, 100, "Dimensionner une solution technique"),
	(112, 111, null),
	(113, null, "Réaliser"),
	(114, 113, "Réaliser et valider un prototype ou une maquette"),
	(115, 114, null),
	(116, 114, null),
	(117, 114, null),
	(118, 114, null),
	(119, 113, "Intégrer des constituants dans un prototype ou une maquette"),
	(120, 119, null),
	(121, 119, null),
	(122, 119, null),
	(123, null, "Communiquer"),
	(124, 123, "Rechercher et traiter des informations"),
	(125, 124, null),
	(126, 124, null),
	(127, 123, "Choisir les contenus et l'outil de description adapté"),
	(128, 123, "Afficher et communiquer des résultats"),
	(129, 20, null),
	(130, 20, null),
	(131, 77, null),
	(132, 124, null),
	(133, 127, null),
	(134, 128, null),
	(135, 128, null),
	(136, 128, null),
	(137, 128, null)
;

INSERT INTO knowledge (id, idParent, name) VALUES
	(1, null, "Outils d’analyse"),
	(2, 1, "Analyse fonctionnelle"),
	(11, 1, "Impact environnemental"),
	(16, 1, "Analyse structurelle"),
	(27, null, "Chaîne d’énergie"),
	(28, 27, "Alimenter en énergie et stocker l’énergie"),
	(36, 28, "Solutions électriques"),
	(40, 28, "Solutions pneumatiques et hydrauliques"),
	(43, 27, "Distribuer et moduler l’énergie"),
	(44, 43, "Moduler l’énergie (convertisseurs statiques d’énergie)"),
	(51, 44, "Solutions électriques relatives à l’entraînement des machines tournantes"),
	(55, 43, "Distribuer l’énergie"),
	(58, 27, "Convertir l’énergie"),
	(59, 58, "Actionneurs et pré-actionneurs associés incluant leurs commandes"),
	(67, 59, "Solutions techniques électriques"),
	(72, 27, "Transmettre l’énergie"),
	(73, 72, "Liaisons mécaniques"),
	(77, 73, "Solutions techniques"),
	(81, 72, "Composants mécaniques de transmission"),
	(84, 81, "Solutions techniques"),
	(87, null, "Chaîne d’information"),
	(88, 87, "Acquérir l’information : capteurs et détecteurs"),
	(94, 87, "Traiter l’information"),
	(95, 94, "Traitement analogique de l’information"),
	(99, 94, "Systèmes programmables"),
	(102, 87, "Communiquer l'information : transport et transmission de l’information"),
	(103, 102, "Conditionnement du signal"),
	(107, 102, "Modes de transmission"),
	(110, 102, "Réseaux"),
	(118, null, "Comportement des systèmes"),
	(119, 118, "Solide indéformable"),
	(120, 119, "Lois de mouvement"),
	(128, 119, "Actions mécaniques"),
	(133, 128, "Approche statique"),
	(137, 128, "Approche dynamique"),
	(142, 128, "Approche énergétique"),
	(148, 118, "Solide déformable"),
	(149, 148, "Comportement du solide déformable"),
	(154, 148, "Caractéristiques des matériaux"),
	(155, 154, "Caractéristiques physiques des matériaux"),
	(160, 154, "Adéquation produits-matériaux-procédés"),
	(165, 118, "Modélisation des systèmes multi-physiques"),
	(166, 165, "Systèmes de commande"),
	(167, 166, "Conditionnement du signal"),
	(171, 166, "Comportement des systèmes logiques"),
	(177, 166, "Comportement des systèmes numériques"),
	(184, 165, "Systèmes asservis multi physique"),
	(185, 184, "Modélisation d’un système asservi multi-physique"),
	(197, 184, "Représentation et identification d’un système asservi"),
	(206, 184, "Performances d’un système asservi"),
	(211, 184, "Contrôle et commande d’un système asservi"),
	(216, 184, "Systèmes non linéaires"),
	(221, null, "Représentation des produits"),
	(222, 221, "Représentation des signaux"),
	(225, 221, "Schématisation des solutions"),
	(227, 225, "Représentation schématique de la structure des chaînes fonctionnelles (mécaniques, électriques, hydrauliques et pneumatiques)"),
	(231, 221, "Représentation géométrique du réel"),
	(237, null, "Protocoles expérimentaux et réalisation"),
	(238, 237, "Protocoles expérimentaux"),
	(245, 237, "Réalisation")
;

INSERT INTO knowledge (id, idParent, name, semester) VALUES
	(3, 2, "Besoin à satisfaire", 1),
	(4, 2, "Cycle de vie du produit", 1),
	(5, 2, "Expression fonctionnelle du besoin", 1),
	(6, 2, "Frontière d’étude", 1),
	(7, 2, "Cahier des charges fonctionnel", 1),
	(8, 2, "Architecture fonctionnelle", 1),
	(9, 2, "Diagramme des exigences", 1),
	(10, 2, "Diagramme des cas d’utilisation", 1),
	(12, 11, "Frontière de l’étude", 1),
	(13, 11, "Contraintes de l’environnement", 1),
	(14, 11, "Bilan carbone", 1),
	(15, 11, "Analyse du Cycle de Vie (ACV)", 1),
	(17, 16, "Diagramme de blocs, diagramme de blocs internes, diagramme paramétrique", 1),
	(18, 16, "Diagramme chaîne d’énergie chaîne d’information", 1),
	(19, 16, "Architecture structurelle", 1),
	(20, 16, "Nature des flux : variables potentielles (tension, vitesse, température…) et variables de flux (courant, force ou couple, flux thermique…)", 1),
	(21, 16, "Architecture fonctionnelle des produits et systèmes : chaîne d’énergie, chaîne d’information", 1),
	(22, 16, "Relations entre chaîne d’énergie et chaîne d’information : grandeurs physiques à acquérir et ordres de commande", 1),
	(23, 16, "Fonctions élémentaires d’une chaîne d’énergie : alimenter, distribuer ou moduler, convertir, transmettre et agir sur la matière d’œuvre", 1),
	(24, 16, "Fonctions élémentaires d’une chaîne d’information : acquérir, traiter et communiquer", 1),
	(25, 16, "Nature, caractéristiques et flux des éléments transformés par le produit : Matière, Énergie et Information", 1),
	(26, 16, "Homogénéité des chaînes fonctionnelles et compatibilité des paramètres d’interface entre les différentes fonctions d’une chaîne", 1),
	(29, 28, "Sources d’énergies", 2),
	(30, 28, "Variables potentielles, variables de flux", 2),
	(31, 28, "Grandeurs physiques disponibles", 2),
	(32, 28, "Constituants de distribution", 2),
	(33, 28, "Sens de transfert de l’énergie, modes de fonctionnement", 2),
	(34, 28, "Batteries, super-condensateurs", 2),
	(35, 28, "Charges inertielles", 3),
	(37, 36, "Réseaux de distribution monophasé et triphasé équilibré", 2),
	(38, 36, "Réseaux embarqués : piles, panneaux solaires et accumulateurs (différentes technologies et leurs principales applications)", 2),
	(39, 36, "Adaptation des niveaux de tension et isolement galvanique (transformateur monophasé parfait)", 2),
	(41, 40, "Accumulateurs ", 3),
	(42, 40, "Pompes", 3),
	(45, 44, "Nature et caractéristiques des grandeurs physiques d’entrée et de sortie : continu ou alternatif, source de courant ou tension parfaite", 2),
	(46, 44, "Caractéristiques statique et dynamique des interrupteurs", 2),
	(47, 44, "Réversibilités (quadrants de fonctionnement)", 2),
	(48, 44, "Règles d’association des sources parfaites – transformation de la nature d’une source", 2),
	(49, 44, "Pertes par conduction", 2),
	(50, 44, "Dissipateur thermique", 2),
	(52, 51, "Conversion alternatif – continu", 2),
	(53, 51, "Conversion continu – continu", 2),
	(54, 51, "Conversion continu – alternatif", 3),
	(56, 55, "Nature et caractéristiques des grandeurs physiques d’entrée et de sortie", 2),
	(57, 55, "Solutions hydrauliques et pneumatiques : distributeurs", 2),
	(60, 59, "Caractéristiques d'entrée et de sortie", 2),
	(61, 59, "Modes de fonctionnement, réversibilités (quadrants de fonctionnement)", 2),
	(62, 59, "Domaines d'application", 2),
	(63, 59, "Principe de la conversion électromécanique", 2),
	(64, 59, "Bilan de puissance", 2),
	(65, 59, "Caractéristiques mécaniques", 2),
	(66, 59, "Association convertisseur-machine-charge", 2),
	(68, 67, "Machine à courant continu à excitation séparée ou à aimant permanent", 2),
	(69, 67, "Machine synchrone triphasée", 3),
	(70, 67, "Machine asynchrone triphasée à cage", 4),
	(71, 67, "Solutions hydrauliques et pneumatiques : vérins, moteurs", 3),
	(74, 73, "Nature des liaisons obtenues", 1),
	(75, 73, "Surfaces fonctionnelles", 1),
	(76, 73, "Caractérisation : niveau de qualité, tenue aux efforts et vitesse relative admissible", 4),
	(78, 77, "Assemblages démontables et permanents", 2),
	(79, 77, "Guidages en rotation par glissement et par éléments roulants", 2),
	(80, 77, "Guidages en translation par glissement et par éléments roulants", 2),
	(82, 81, "Caractérisation cinématique de la transmission : mobilités, loi d’entrée-sortie et réversibilité", 1),
	(83, 81, "Puissances d’entrée, de sortie et rendement en un point de fonctionnement", 3),
	(85, 84, "Transmissions sans transformation de mouvement, sans et avec modification de la fréquence de rotation", 2),
	(86, 84, "Transmissions avec transformation de mouvement", 2),
	(89, 88, "Place du capteur dans la chaîne d’information", 1),
	(90, 88, "Fonctions de base et structure fonctionnelle de la chaîne d’acquisition de l’information (principes physiques de l’acquisition de l’information)", 1),
	(91, 88, "Nature des informations d’entrée et de sortie", 1),
	(92, 88, "Caractéristiques métrologiques : étendue de mesure, sensibilité, résolution, justesse, fidélité, précision et temps de réponse", 2),
	(93, 88, "Paramètres d’un capteur communicant", 4),
	(96, 95, "Filtrage (1)", 1),
	(97, 95, "Opérations élémentaires (addition, soustraction, multiplication, saturation)", 1),
	(98, 95, "Conversions A/N et N/A : approche fonctionnelle (3)", 1),
	(100, 99, "Structure fonctionnelle des systèmes programmables", 2),
	(101, 99, "Solutions techniques : microcontrôleur, circuit logique programmable", 2),
	(104, 103, "Caractéristiques principales : bande passante et atténuation", 1),
	(105, 103, "Modulation et démodulation d’amplitude (1)", 4),
	(106, 103, "Modulation de largeur d’impulsion (MLI)", 2),
	(108, 107, "Modes de transmission série : mise en œuvre d’une transmission série asynchrone", 4),
	(109, 107, "Topologie, sens de transfert", 4),
	(111, 110, "Architecture matérielle et fonctionnelle des réseaux : supports de l’information, topologie, sens de transfert", 4),
	(112, 110, "Caractéristiques d’un canal de transmission", 4),
	(113, 110, "Multiplexage temporel et fréquentiel", 4),
	(114, 110, "Notion de protocole : rôle des champs dans une trame", 4),
	(115, 110, "Architecture protocolaire : organisation en couches fonctionnelles", 4),
	(116, 110, "Adressage physique et logique d’un constituant", 4),
	(117, 110, "Solutions techniques : les paires torsadées, les fibres optiques et les liaisons sans fil", 4),
	(121, 120, "Mouvement d’un solide, trajectoire d’un point d’un solide", 1),
	(122, 120, "Vecteur position, vecteur vitesse et vecteur accélération", 1),
	(123, 120, "Torseur cinématique associé à une liaison", 1),
	(124, 120, "Liaison équivalente à une association de deux liaisons en série ou en parallèle", 1),
	(125, 120, "Loi d’entrée-sortie en vitesse et en position d’un système", 1),
	(126, 120, "Degré de mobilité et degré d’hyperstatisme (1)", 2),
	(127, 120, "Conditions géométriques associées à l’hyperstatisme", 2),
	(129, 128, "Modélisation des actions mécaniques", 2),
	(130, 128, "Nature : action mécanique de contact et action mécanique à distance (gravité et magnétique)", 2),
	(131, 128, "Modèle local du contact : notion de densité surfacique de charge et modèles de répartition sur une surface de contact (sans frottement et avec frottement - lois de Coulomb)", 2),
	(132, 128, "Modèle global des actions transmissibles par une liaison parfaite ou non parfaite : torseur associé", 2),
	(134, 133, "Conditions d’utilisation et application du Principe Fondamental de la Statique", 2),
	(135, 133, "Théorème des actions réciproques", 2),
	(136, 133, "Méthodologie : isolement, bilan des actions mécaniques extérieures, application du Principe Fondamental de la Statique (PFS) et résolution", 2),
	(138, 137, "Grandeurs inertielles : centre d’inertie, masse, opérateur d’inertie / matrice associée et théorème de Huygens", 3),
	(139, 137, "Grandeurs cinétiques : torseur cinétique, torseur dynamique et énergie cinétique", 3),
	(140, 137, "Conditions d’utilisation et application du Principe Fondamental de la Dynamique par rapport à un référentiel galiléen", 3),
	(141, 137, "Méthodologie : isolement, bilan des actions mécaniques extérieures, application du Principe Fondamental de la Dynamique (PFD) et résolution", 3),
	(143, 142, "Puissances développées par les actions mécaniques extérieures à l’ensemble isolé dans son mouvement par rapport à un référentiel galiléen", 3),
	(144, 142, "Puissances développées à l’intérieur de l’ensemble isolé", 3),
	(145, 142, "Utilisation du théorème de l’énergie cinétique galiléenne", 3),
	(146, 142, "Notion de pertes de puissance et rendement global en un point de fonctionnement", 3),
	(147, 142, "Méthodologie : isolement, bilan des puissances, application du théorème de l’énergie cinétique galiléenne et résolution", 3),
	(150, 149, "Flexion simple, torsion simple, traction–compression", 4),
	(151, 149, "Sollicitations, contraintes, déformations", 4),
	(152, 149, "Torseur de cohésion", 4),
	(153, 149, "Coefficient de sécurité, résistance mécanique", 4),
	(156, 155, "Caractéristiques dans les domaines de l’électricité, du thermique, de l’acoustique et de la mécanique", 3),
	(157, 155, "Matériaux composites", 4),
	(158, 155, "Nano matériaux", 4),
	(159, 155, "Familles de matériaux", 3),
	(161, 160, "Procédés d’obtention des produits", 2),
	(162, 160, "Paramètres influents du procédé : matériaux, géométrie, précision", 2),
	(163, 160, "Choix d’un matériau en fonction du design du produit", 3),
	(164, 160, "Démarche de choix du couple matériaux-procédé", 4),
	(168, 167, "Filtrage analogique passif : réalisation de filtres passifs", 2),
	(169, 167, "Dualité temps / fréquence", 2),
	(170, 167, "Conversions analogique–numérique et numérique-analogique, caractéristiques : fréquence d’échantillonnage, et résolution", 2),
	(172, 171, "Identification des entrées / sorties", 1),
	(173, 171, "Notion d’état logique, de fonctions logiques", 1),
	(174, 171, "Description d’un système logique par une table de vérité ou d’un logigramme", 1),
	(175, 171, "Description d’un système logique par un graphe d’état", 1),
	(176, 171, "Notions d’état, transitions et variables", 1),
	(178, 177, "Identification des entrées / sorties", 1),
	(179, 177, "Adressage des variables", 1),
	(180, 177, "Boucles", 1),
	(181, 177, "Transitions conditionnelles", 1),
	(182, 177, "Fonctions", 1),
	(183, 177, "Description d’un système numérique par algorigramme", 1),
	(186, 185, "Introduction - aspects généraux", 1),
	(187, 185, "Buts et motivations, exemples", 1),
	(188, 185, "Définition et structure d'un système asservi : chaîne directe et chaîne de retour", 1),
	(189, 185, "Consigne et perturbations", 3),
	(190, 185, "Asservissement - régulation", 3),
	(191, 185, "Définition des performances : stabilité, précision et rapidité", 3),
	(192, 185, "Modélisation et comportement des systèmes linéaires continus et invariants", 3),
	(193, 185, "Notions de systèmes linéaires continus et invariants", 3),
	(194, 185, "Modélisation par équations différentielles", 3),
	(195, 185, "Représentation par fonction de transfert : forme canonique, gain, ordre et classe", 3),
	(196, 185, "Systèmes du 1er et du 2nd ordre : réponses temporelle (échelon et signal sinusoïdal) et fréquentielle (diagramme de Bode uniquement)", 3),
	(198, 197, "Systèmes linéaires, continus et invariants", 3),
	(199, 197, "Linéarisation autour d’un point de fonctionnement", 3),
	(200, 197, "Représentation par schémas–blocs", 3),
	(201, 197, "Fonctions de transfert en boucle ouverte et en boucle fermée, influence des perturbations", 3),
	(202, 197, "Représentation dans le plan de Bode (asymptotique et réel)", 3),
	(203, 197, "Identification des systèmes linéaires continus et invariants : modélisation et identification paramétrique à l’aide d’une réponse indicielle et/ou d’une réponse harmonique pour les systèmes du 1er et du 2nd ordre", 3),
	(204, 197, "Position des pôles dans le plan complexe", 3),
	(205, 197, "Pôles dominants et réduction du modèle", 3),
	(207, 206, "Stabilité en BO : position des pôles, marges de phase et de gain dans le plan de Bode", 3),
	(208, 206, "Précision : erreur en régime permanent pour une réponse indicielle ou rampe", 3),
	(209, 206, "Effet d'une action intégrale dans la chaîne directe", 3),
	(210, 206, "Rapidité : temps de réponse à 5 %, dépassement et bande passante en boucle ouverte", 3),
	(212, 211, "Correction des systèmes asservis, classe d’une fonction de transfert", 3),
	(213, 211, "Effets sur les performances", 3),
	(214, 211, "Régulateurs P, PI, avance de phase", 3),
	(215, 211, "Discrétisation d’un correcteur", 3),
	(217, 216, "Hystérésis", 3),
	(218, 216, "Saturation", 3),
	(219, 216, "Seuil", 3),
	(220, 216, "Retard", 3),
	(223, 222, "Représentation logique : binaire et hexadécimale des nombres entiers et nombres réels (positif et négatif, virgule fixe et flottante simple précision)", 1),
	(224, 222, "Représentations temporelle (chronogramme) et fréquentielle (spectre), représentation dans le plan complexe", 2),
	(226, 225, "Schéma cinématique, schéma cinématique minimal, schéma d’architecture", 1),
	(228, 227, "Schémas électriques, hydrauliques et pneumatiques", 1),
	(229, 227, "Graphe de structure", 1),
	(230, 227, "Schéma informatique : description graphique", 4),
	(232, 231, "Dessin et croquis à main levée d’une solution", 1),
	(233, 231, "Représentation d’une solution constructive en 3D par un modeleur volumique", 1),
	(234, 231, "Assemblage sous contrainte", 1),
	(235, 231, "Cotation GPS, MMT", 4),
	(236, 231, "Utilisation de bibliothèques d’éléments standards", 1),
	(239, 238, "Environnement du système", 1),
	(240, 238, "Mise en œuvre d’un système, paramètres de fonctionnement d’un système", 1),
	(241, 238, "Choix des appareils de mesures (position, calibre, période d’échantillonnage, précision)", 1),
	(242, 238, "Amplitude des grandeurs, caractéristiques fréquentielle et temporelle", 1),
	(243, 238, "Respect des normes de sécurité, protection des biens et des personnes", 1),
	(244, 238, "Respect d’un protocole expérimental", 1),
	(246, 245, "Prototypage rapide", 3),
	(247, 245, "Prototype", 3),
	(248, 245, "Facteurs d’échelle, grandeurs influentes", 3),
	(249, 245, "Assemblage des constituants", 3),
	(250, 245, "Programmation des constituants", 3),
	(251, 245, "Mise en œuvre d’un réseau", 3),
	(252, 245, "Caractéristiques dimensionnelle et géométrique de pièces", 3),
	(253, 245, "Méthodes de mesures", 3)
;

INSERT INTO knowHow (idCompetence, name) VALUES
	(3, "Décrire le besoin"),
	(3, "Présenter la fonction globale"),
	(3, "Identifier les domaines d’application, les critères technico-économiques"),
	(3, "Identifier les contraintes"),
	(3, "Qualifier et quantifier les exigences (critères, niveaux)"),
	(3, "Identifier et caractériser les fonctions de service"),
	(4, "Évaluer l’impact environnemental (matériaux, énergie, nuisances)"),
	(4, "Établir une analyse du cycle de vie (ACV) et analyser les résultats"),
	(4, "Effectuer un bilan carbone"),
	(6, "Définir les éléments influents du milieu extérieur"),
	(6, "Identifier les contraintes"),
	(7, "Isoler un système et justifier l’isolement"),
	(7, "Définir les limites et les contraintes choisies ou imposées"),
	(9, "Identifier les fonctions techniques"),
	(9, "Déterminer les constituants dédiés aux fonctions d’un système et en justifier le choix"),
	(9, "Identifier les architectures fonctionnelles et structurelles"),
	(10, "Identifier la structure d'un système asservi : chaîne directe, capteur, commande (fonction différence, correction)"),
	(10, "Identifier et positionner les perturbations"),
	(10, "Différencier régulation et asservissement"),
	(11, "Identifier la nature des flux échangés (Matière, Énergie, Information) traversant la frontière d’étude"),
	(11, "Préciser leurs caractéristiques (variable potentielle, variable flux)"),
	(11, "Identifier et décrire les chaînes d’information et d’énergie d’un système"),
	(11, "Identifier les constituants réalisant les fonctions : acquérir, traiter, communiquer, alimenter, distribuer, moduler, convertir, transmettre et agir"),
	(11, "Identifier la nature et les caractéristiques des flux échangés"),
	(11, "Vérifier l’homogénéité et la compatibilité des flux entre les différents constituants"),
	(12, "Identifier les liens entre chaîne d’énergie et chaîne d’information"),
	(12, "Analyser l’effet de la commande sur le comportement de la chaîne d’énergie"),
	(12, "Analyser la réversibilité de la chaine d’énergie"),
	(13, "Analyser le comportement d’un système décrit par un graphe d’état ou un logigramme"),
	(14, "Analyser et interpréter un algorigramme ou un algorithme (écrit en pseudo-code)"),
	(15, "Identifier les architectures matérielles et fonctionnelles d’un réseau de communication"),
	(15, "Déterminer le mode de transmission"),
	(15, "Décoder une trame en vue d’analyser les différents champs"),
	(16, "Identifier les contraintes, les déformations et les sollicitations d’un solide"),
	(17, "Identifier les familles des matériaux et analyser le choix des matériaux vis-à-vis des performances attendues"),
	(18, "Identifier et caractériser un capteur"),
	(19, "Analyser une spécification indiquée sur un dessin de définition par rapport aux contraintes de montage et de réalisation"),
	(21, "Exploiter et interpréter les résultats d’un calcul ou d’une simulation (analyse de la modélisation proposée et des résultats obtenus)"),
	(21, "Traiter des données de mesures et de simulations et extraire les caractéristiques statistiques"),
	(21, "Extraire du cahier des charges les grandeurs pertinentes"),
	(129, "Quantifier des écarts entre des valeurs attendues et des valeurs mesurées"),
	(129, "Quantifier des écarts entre des valeurs attendues et des valeurs obtenues par simulation"),
	(129, "Quantifier des écarts entre des valeurs mesurées et des valeurs obtenues par simulation"),
	(130, "Rechercher et proposer des causes aux écarts constatés"),
	(130, "Vérifier la cohérence du modèle choisi avec des résultats d’expérimentation"),
	(23, "Prévoir l’ordre de grandeur et l’évolution de la mesure ou de la simulation"),
	(23, "Critiquer les résultats issus d’une mesure ou d’une simulation"),
	(23, "Identifier des valeurs erronées"),
	(23, "Analyser la pertinence du choix des grandeurs simulées"),
	(23, "Valider ou affirmer une hypothèse"),
	(24, "Exploiter et interpréter des résultats de mesure ou de simulation"),
	(24, "Utiliser des symboles et des unités adéquates"),
	(24, "Vérifier l’homogénéité des résultats"),
	(27, "Qualifier les grandeurs d’entrée et de sortie d’un système isolé"),
	(28, "Décrire les évolutions temporelles ou fréquentielles des grandeurs dans les chaînes d’énergie et d’information"),
	(29, "Associer les grandeurs physiques aux échanges d’énergie et à la transmission de puissance"),
	(29, "Identifier les pertes d’énergie dans un convertisseur statique d’énergie, dans un actionneur ou dans une liaison"),
	(30, "Identifier la nature de l’information et la nature du signal"),
	(31, "Identifier les phénomènes dominants"),
	(31, "Proposer des hypothèses simplificatrices en vue de la modélisation"),
	(33, "Associer un modèle aux constituants d’une chaîne d’énergie"),
	(34, "Modéliser l’association convertisseur statique-machine"),
	(35, "Proposer et justifier un modèle de liaison entre deux solides"),
	(35, "Associer aux liaisons un torseur d’action mécanique transmissible et un torseur cinématique"),
	(35, "Déterminer la liaison cinématiquement équivalente à un ensemble de liaisons"),
	(36, "Paramétrer les mouvements d’un solide indéformable"),
	(37, "Réaliser le graphe de structure de tout ou partie d’un mécanisme"),
	(37, "Proposer un schéma cinématique (plan ou 3D) minimal et d’architecture de tout ou partie d’un mécanisme"),
	(38, "Réaliser l’inventaire des actions mécaniques extérieures s’exerçant sur un solide ou un ensemble de solides"),
	(39, "Choisir un modèle de solide (indéformable ou déformable) en fonction de l’objectif visé"),
	(40, "Déterminer les caractéristiques d’un solide indéformable (masse, centre d’inertie, matrice d’inertie)"),
	(41, "Associer un modèle à une action mécanique"),
	(41, "Ecrire la relation entre modèle local et modèle global dans le cas d’actions réparties"),
	(42, "Déterminer le torseur de cohésion dans un solide"),
	(42, "Associer un modèle de contraintes à l’état de sollicitation"),
	(43, "Proposer ou justifier des conditions aux limites dans un logiciel de simulation par éléments finis"),
	(44, "Adapter la typologie d’un convertisseur statique à la nature des sources"),
	(45, "Établir le schéma bloc du système"),
	(46, "Déterminer les fonctions de transfert à partir d’équations physiques (modèle de connaissance)"),
	(46, "Déterminer les fonctions de transfert en boucle ouverte et boucle fermée"),
	(47, "Linéariser un modèle autour d’un point de fonctionnement"),
	(48, "Identifier les paramètres caractéristiques d’un modèle du premier ou du second ordre à partir de sa réponse indicielle"),
	(49, "Identifier les paramètres d’un modèle de comportement à partir d’un diagramme de Bode"),
	(49, "Associer un modèle de comportement (premier et second ordre, dérivateur, intégrateur) à partir d’un diagramme de Bode"),
	(50, "Définir les paramètres du modèle"),
	(50, "Utiliser un diagramme paramétrique"),
	(52, "Vérifier la cohérence du modèle choisi avec les résultats d’expérimentation"),
	(53, "Réduire l’ordre de la fonction de transfert selon l’objectif visé, à partir des pôles dominants qui déterminent la dynamique asymptotique du système"),
	(54, "Modifier les paramètres et enrichir le modèle pour minimiser l’écart entre les résultats simulés et les réponses mesurées"),
	(55, "Donner les limites de validité d’un modèle"),
	(58, "Proposer une démarche permettant de prévoir les performances d’un système asservi"),
	(59, "Proposer une démarche de réglage d’un correcteur proportionnel"),
	(60, "Proposer une démarche permettant de déterminer une loi de mouvement"),
	(61, "Proposer une méthode permettant la détermination des inconnues de liaison"),
	(61, "Proposer une méthode permettant la détermination des paramètres conduisant à des positions d'équilibre"),
	(62, "Proposer une méthode de résolution permettant la détermination des courants, des tensions, des puissances échangées, des énergies transmises ou stockées"),
	(64, "Prévoir les réponses temporelles des systèmes linéaires du premier et second ordre"),
	(64, "Prévoir les réponses fréquentielles des systèmes linéaires"),
	(65, "Caractériser la stabilité d’un système du premier et du second ordre"),
	(65, "Justifier le choix d’un correcteur vis-à-vis des performances attendues"),
	(66, "Déterminer des paramètres permettant d’assurer la stabilité, en s’appuyant sur les tracés fréquentiels dans le plan de Bode"),
	(66, "Déterminer l’erreur en régime permanent vis-à-vis d’une entrée en échelon ou en rampe (consigne ou perturbation)"),
	(67, "Prévoir les performances de rapidité et de précision d’un système linéaire continu et invariant"),
	(68, "Déterminer la loi entrée-sortie d’une chaîne cinématique simple"),
	(68, "Déterminer la trajectoire d’un point d’un solide par rapport à un autre"),
	(68, "Déterminer le vecteur vitesse d’un point d’un solide par rapport à un autre"),
	(68, "Déterminer le vecteur accélération d’un point d’un solide par rapport à un autre"),
	(68, "Déterminer les relations de fermeture géométrique et cinématique d’une chaîne cinématique, et résoudre le système associé Déterminer le degré de mobilité et d’hyperstatisme"),
	(69, "Déterminer les inconnues de liaison"),
	(69, "Déterminer les paramètres conduisant à des positions d'équilibre"),
	(70, "Déterminer les inconnues de liaison ou les efforts extérieurs spécifiés dans le cas où le mouvement est imposé"),
	(70, "Ecrire le torseur dynamique d’un solide en mouvement au centre de masse ou en un point fixe du solide dans un référentiel galiléen"),
	(71, "Donner la loi du mouvement sous forme d'équations différentielles dans le cas où les efforts extérieurs sont connus"),
	(71, "Exprimer l’énergie cinétique d’un solide dans un référentiel galiléen"),
	(71, "Exprimer les puissances extérieures et les inter-efforts"),
	(71, "Exprimer le théorème de l’énergie-puissance appliqué à tout ou partie des éléments de la chaîne d’énergie"),
	(72, "Construire graphiquement les lois de l’électricité à partir des vecteurs de Fresnel"),
	(73, "Déterminer les pertes en conduction dans un interrupteur statique"),
	(73, "Dimensionner un dissipateur thermique"),
	(74, "Déterminer la répartition des contraintes dans une section droite"),
	(74, "Vérifier la résistance mécanique d’une poutre droite"),
	(74, "Déterminer le coefficient de sécurité par rapport aux exigences du cahier des charges fonctionnel"),
	(74, "Déterminer l’équation de la flèche dans une poutre droite soumise à de la flexion, avec chargements ponctuels ou répartition linéique constante de la charge"),
	(75, "Déterminer les courants et les tensions dans les composants"),
	(75, "Déterminer les puissances échangées"),
	(75, "Déterminer les énergies transmises ou stockées"),
	(76, "Déterminer les caractéristiques mécaniques de l’actionneur"),
	(76, "Déterminer le point de fonctionnement"),
	(78, "Choisir une méthode d’intégration adaptée au modèle à simuler"),
	(78, "Choisir une durée de simulation adaptée au comportement à observer"),
	(79, "Utiliser le diagramme paramétrique pour renseigner un modèle"),
	(79, "Choisir et justifier le choix des grandeurs simulées"),
	(79, "Qualifier l’influence d’un paramètre sur les performances simulées"),
	(131, "Mettre en place des simulations d’obtention de pièces brutes par fonderie, injection plastique, forgeage, emboutissage, et de pièces finies par enlèvement de matière"),
	(82, "Mettre en œuvre un système dans le respect des règles de sécurité"),
	(83, "Identifier les constituants réalisant les fonctions élémentaires de la chaîne d’énergie et d’information"),
	(83, "Repérer les flux d’entrée et de sortie de chaque constituant, leurs natures (électrique, mécanique, pneumatique, thermique ou hydraulique) et leurs sens de transfert)."),
	(85, "Prévoir l’allure de la réponse attendue"),
	(85, "Prévoir l’ordre de grandeur de la mesure"),
	(86, "Choisir les configurations matérielles du système en fonction de l’objectif visé"),
	(86, "Justifier le choix de la grandeur physique à mesurer"),
	(86, "Choisir les entrées à imposer pour identifier un modèle de comportement"),
	(87, "Choisir les appareillages et les conditions d’exploitation en adéquation avec la législation"),
	(87, "Proposer et justifier le lieu de prise de mesures vis-à-vis de l’objectif à atteindre"),
	(88, "Qualifier les caractéristiques d’entrée-sortie d’un capteur"),
	(88, "Justifier le choix d’un capteur ou d’un appareil de mesure vis-à-vis de la grandeur physique à mesurer"),
	(88, "Justifier les caractéristiques d’un appareil de mesure"),
	(89, "Proposer les paramètres de configuration d’une chaîne d’acquisition (capteurs intelligents, conditionneur, réseaux)"),
	(90, "Prévoir la quantification nécessaire à la précision souhaitée Vérifier l’adéquation entre le temps de conversion et la fréquence d’échantillonnage"),
	(92, "Mettre en œuvre un appareil de mesure adapté à la caractéristique de la grandeur à mesurer"),
	(93, "Paramétrer une chaîne d’acquisition en fonction des caractéristiques des capteurs et des résultats de mesures attendus"),
	(93, "Paramétrer les constituants d’un réseau local"),
	(94, "Choisir une fenêtre d’observation en fonction des résultats attendus"),
	(95, "Régler les paramètres de fonctionnement d’un système"),
	(96, "Mesurer les grandeurs potentielles et les grandeurs de flux dans les différents constituants d’une chaîne d’énergie"),
	(97, "Générer un programme et l’implanter dans le système cible"),
	(97, "Réaliser une intégration ou une dérivée sous forme numérique (somme et différence)"),
	(98, "Mettre en œuvre un système complexe en respectant les règles de sécurité"),
	(98, "Respecter les protocoles expérimentaux"),
	(99, "Effectuer des traitements (filtrage, régression linéaire, méthode des moindres carrés, analyse statistique, …) à l’aide de logiciels adaptés à partir des données de mesures expérimentales"),
	(102, "Proposer une architecture fonctionnelle de tout ou partie d’un système en vue de sa conception"),
	(102, "Proposer une architecture structurelle de tout ou partie d’un système en vue de sa conception"),
	(103, "Elaborer la maquette numérique de la partie étudiée du produit en intégrant les contraintes fonctionnelles d’assemblage"),
	(104, "Proposer des évolutions sous forme fonctionnelle"),
	(104, "Modifier une programmation à l’aide des outils graphe d’états, logigramme ou algorigramme"),
	(106, "Choisir un convertisseur en fonction des transferts énergétiques souhaités"),
	(107, "Choisir un actionneur adapté à la solution constructive"),
	(108, "Choisir un correcteur adapté aux performances attendues"),
	(108, "Discrétiser un correcteur analogique"),
	(109, "Choisir un matériau ou une famille de matériau avec des objectifs multicritères"),
	(110, "Proposer et hiérarchiser des critères de choix d’une solution technique"),
	(110, "Choisir et justifier la solution technique retenue"),
	(112, "Dimensionner les constituants de la chaîne d’énergie et de la chaîne d’information à partir d’une documentation technique"),
	(115, "Réaliser un prototype de tout ou partie d’un système en vue de valider l’architecture fonctionnelle et structurelle"),
	(116, "Mettre en place un asservissement à l’aide de constituants numériques"),
	(117, "Valider les choix des composants vis-à-vis des performances attendues"),
	(117, "Analyser les facteurs d’échelle et les proportions des grandeurs influentes"),
	(118, "Mesurer des caractéristiques dimensionnelle et géométrique de pièces"),
	(118, "Définir les méthodes de mesures"),
	(120, "Assembler un ou plusieurs constituants pour permettre de répondre à une fonction technique"),
	(121, "Mettre en œuvre des composants programmables à l’aide d’un outil graphique de description (graphe d’état, algorigramme, …) en y intégrant les constituants réalisant les interfaces entre les grandeurs d’entrées et de sorties"),
	(122, "Identifier le ou les élément(s) limitant(s) du point de vue des performances globales du prototype"),
	(125, "Extraire les informations utiles d’un dossier technique"),
	(125, "Effectuer une synthèse des informations disponibles dans un dossier technique Vérifier la nature des informations"),
	(125, "Définir les critères de tri des informations"),
	(125, "Trier les informations selon des critères"),
	(125, "Distinguer les différents types de documents en fonction de leurs usages"),
	(126, "Lire et interpréter un schéma"),
	(132, "Lire et interpréter un diagramme"),
	(133, "Cibler le contenu de la communication et choisir l’outil de description adapté"),
	(134, "Utiliser les outils de communication adaptés à son auditoire"),
	(135, "Avoir une attitude conforme à l’éthique"),
	(135, "Respecter son temps de parole"),
	(135, "Être attentif aux réactions de son auditoire"),
	(135, "Faire preuve d’écoute et confronter des points de vue"),
	(136, "Être capable de reformuler un questionnement"),
	(137, "Synthétiser des informations sous une forme écrite ou orale")
;

INSERT INTO knowledgeByCompetence (idCompetence, idKnowledge) VALUES
	(3, 2),
	(4, 11),
	(6, 11),
	(7, 2),
	(7, 16),
	(9, 2),
	(9, 16),
	(10, 184),
	(11, 16),
	(12, 27),
	(12, 87),
	(13, 171),
	(14, 177),
	(15, 102),
	(16, 148),
	(17, 154),
	(18, 88),
	(19, 245),
	(23, 118),
	(24, 237),
	(27, 16),
	(27, 118),
	(28, 16),
	(28, 222),
	(29, 27),
	(30, 87),
	(31, 16),
	(33, 27),
	(34, 43),
	(34, 58),
	(35, 73),
	(35, 120),
	(36, 120),
	(37, 225),
	(38, 128),
	(38, 133),
	(39, 119),
	(39, 148),
	(40, 137),
	(41, 133),
	(42, 149),
	(43, 149),
	(44, 43),
	(45, 184),
	(46, 197),
	(47, 185),
	(47, 216),
	(48, 197),
	(49, 185),
	(49, 197),
	(50, 185),
	(52, 185),
	(53, 197),
	(54, 185),
	(55, 216),
	(58, 184),
	(59, 211),
	(60, 120),
	(61, 128),
	(62, 28),
	(62, 44),
	(62, 58),
	(64, 184),
	(64, 222),
	(65, 206),
	(66, 211),
	(66, 222),
	(67, 206),
	(68, 120),
	(69, 128),
	(70, 128),
	(71, 120),
	(71, 128),
	(72, 28),
	(72, 59),
	(73, 43),
	(74, 148),
	(75, 28),
	(75, 43),
	(76, 58),
	(79, 16),
	(131, 160),
	(82, 238),
	(83, 27),
	(83, 87),
	(83, 16),
	(85, 222),
	(86, 238),
	(87, 238),
	(87, 16),
	(88, 88),
	(89, 87),
	(90, 167),
	(92, 238),
	(93, 87),
	(94, 222),
	(95, 238),
	(96, 27),
	(96, 16),
	(97, 171),
	(97, 177),
	(98, 238),
	(99, 94),
	(102, 2),
	(102, 16),
	(103, 225),
	(103, 231),
	(104, 2),
	(104, 171),
	(104, 177),
	(106, 27),
	(107, 58),
	(108, 211),
	(109, 11),
	(109, 154),
	(110, 11),
	(110, 27),
	(110, 87),
	(112, 27),
	(112, 87),
	(115, 245),
	(116, 211),
	(117, 245),
	(118, 245),
	(120, 245),
	(121, 177),
	(122, 16),
	(126, 225),
	(132, 165),
	(130, 16),
	(130, 118)
;

COMMIT;